[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

# Add this to explicitly include the .env file during development
[build.environment]
  NODE_ENV = "development"